project:
  type: website
  output-dir: docs

website:
  title: "Ankush Garg - Personal Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/garg-ankush
  google-analytics: "${{ secrets.GOOGLE_ANALYTICS_ID }}"
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual